name: "Test action-ros-lint"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    # Run the CI automatically every hour to look for flakyness.
    - cron:  '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    - run: |
        git clone --depth=1 --branch=0.8.1 \
            https://github.com/ament/ament_lint.git
    - uses: ros-tooling/setup-ros@0.0.16
    - name: Try default linter
      uses: ./
      with:
        package-name: ament_copyright ament_lint
        workspace-directory: ament_lint
    - name: Try a linter with underscores in the name
      uses: ./
      with:
        linter: lint_cmake
        package-name: ament_cmake_cpplint
        workspace-directory: ament_lint
