name: "Test action-ros2-lint"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build

    - uses: thomas-moulard/setup-ros2@0.0.3
    - uses: ./ # Uses an action in the root directory
      with:
        package-name: ament_copyright
